
import localFont from 'next/font/local'
import styles from './page.module.css'
import './globals.css'
const f = localFont({ src: '../fonts/Joscelyn/Joscelyn.woff2' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{background: "#fc0", height: "100vh", overflow: "hidden"}}  className={`${f.className} ${styles.header}`}>{children}</body>
    </html>
  )
}
